### ISSUE TITLE
你好，请问有继续开发股票数据的获取

### ISSUE THREAD

**Issue by 85636682** [yinhm/datafeed#2]
你好，请问有继续开发股票数据的获取，有一些问题想请教你！

**Comment by yinhm** [comment]
Hi，暂时没有新的计划，因为我们暂时也没有新的需求。不知道你有什么问题，不放直接提出。

**Comment by 85636682** [comment]
其实我对这方面经验是0！这些有点涉及各公司秘密，比较少文档，我想学习下。你们获取数据的流程是，读取大智慧之类的本地文件，然后分析，再上传到自己的服务器吗？

**Comment by zhenning** [comment]
我们不是手动上传到服务器的，你可以看看datafeed /providers有几种方式。
